// GENERATED by scripts/build-hero.ts — do not edit by hand.
// Landing-hero photo set (المسجد النبوي الشريف), served from /public/hero.
// URLs follow the -400/-800/-1600.webp convention so PlaceImage's variantUrl
// and capMobile work unchanged.

export type HeroImage = { url: string; width: number; height: number };

export const HERO_IMAGES: HeroImage[] = [
  { url: "/hero/hero-e1dcbfabce-1600.webp", width: 1288, height: 1718 },
  { url: "/hero/hero-4cb98b47fc-1600.webp", width: 1600, height: 2133 },
  { url: "/hero/hero-ac41c2196f-1600.webp", width: 1600, height: 2130 },
  { url: "/hero/hero-0d6bdedf09-1600.webp", width: 1600, height: 2138 },
  { url: "/hero/hero-2b630b002b-1600.webp", width: 1600, height: 1202 },
  { url: "/hero/hero-c5f345ea52-1600.webp", width: 1600, height: 2138 },
  { url: "/hero/hero-f77df43d28-1600.webp", width: 1600, height: 2138 },
  { url: "/hero/hero-5305b22cc4-1600.webp", width: 1600, height: 1197 },
  { url: "/hero/hero-0c0a55d78b-1600.webp", width: 1600, height: 2138 },
  { url: "/hero/hero-3e273e6f01-1600.webp", width: 1600, height: 1031 },
  { url: "/hero/hero-32ea614a01-1600.webp", width: 1600, height: 900 },
];
