// GENERATED by scripts/build-nabawi.ts — do not edit by hand.
// المسجد النبوي chapter of /tour: 23 photos,
// 11 videos, served from R2 via media.mazarat-madinah.com (nabawi/).

export type NabawiMedia = {
  kind: "photo" | "video";
  url: string;
  poster?: string;
  width: number;
  height: number;
  durationSeconds?: number;
};

export const NABAWI_MEDIA: NabawiMedia[] = [
  { kind: "video", url: "https://media.mazarat-madinah.com/nabawi/7ecba0c913.mp4", poster: "https://media.mazarat-madinah.com/nabawi/7ecba0c913-poster-800.jpg", width: 800, height: 450, durationSeconds: 16 },
  { kind: "photo", url: "https://media.mazarat-madinah.com/nabawi/ac41c2196f-1600.webp", width: 1600, height: 2130 },
  { kind: "photo", url: "https://media.mazarat-madinah.com/nabawi/0d6bdedf09-1600.webp", width: 1600, height: 2138 },
  { kind: "photo", url: "https://media.mazarat-madinah.com/nabawi/2b630b002b-1600.webp", width: 1600, height: 1202 },
  { kind: "photo", url: "https://media.mazarat-madinah.com/nabawi/dfe2bd2f99-1600.webp", width: 1600, height: 2138 },
  { kind: "photo", url: "https://media.mazarat-madinah.com/nabawi/c5f345ea52-1600.webp", width: 1600, height: 2138 },
  { kind: "photo", url: "https://media.mazarat-madinah.com/nabawi/f77df43d28-1600.webp", width: 1600, height: 2138 },
  { kind: "video", url: "https://media.mazarat-madinah.com/nabawi/5e074a7cee.mp4", poster: "https://media.mazarat-madinah.com/nabawi/5e074a7cee-poster-800.jpg", width: 800, height: 450, durationSeconds: 4 },
  { kind: "photo", url: "https://media.mazarat-madinah.com/nabawi/5305b22cc4-1600.webp", width: 1600, height: 1197 },
  { kind: "photo", url: "https://media.mazarat-madinah.com/nabawi/4bbebf9794-1600.webp", width: 1600, height: 2138 },
  { kind: "video", url: "https://media.mazarat-madinah.com/nabawi/16077f0d29.mp4", poster: "https://media.mazarat-madinah.com/nabawi/16077f0d29-poster-800.jpg", width: 720, height: 1280, durationSeconds: 5 },
  { kind: "photo", url: "https://media.mazarat-madinah.com/nabawi/4a2c371a8f-1600.webp", width: 1600, height: 2138 },
  { kind: "video", url: "https://media.mazarat-madinah.com/nabawi/6ac419a56a.mp4", poster: "https://media.mazarat-madinah.com/nabawi/6ac419a56a-poster-800.jpg", width: 720, height: 1280, durationSeconds: 6 },
  { kind: "photo", url: "https://media.mazarat-madinah.com/nabawi/0c0a55d78b-1600.webp", width: 1600, height: 2138 },
  { kind: "video", url: "https://media.mazarat-madinah.com/nabawi/0f5a74e471.mp4", poster: "https://media.mazarat-madinah.com/nabawi/0f5a74e471-poster-800.jpg", width: 720, height: 1280, durationSeconds: 10 },
  { kind: "video", url: "https://media.mazarat-madinah.com/nabawi/3b5c59eb45.mp4", poster: "https://media.mazarat-madinah.com/nabawi/3b5c59eb45-poster-800.jpg", width: 720, height: 1280, durationSeconds: 17 },
  { kind: "photo", url: "https://media.mazarat-madinah.com/nabawi/3e273e6f01-1600.webp", width: 1600, height: 1031 },
  { kind: "video", url: "https://media.mazarat-madinah.com/nabawi/bfb9cfba01.mp4", poster: "https://media.mazarat-madinah.com/nabawi/bfb9cfba01-poster-800.jpg", width: 720, height: 1280, durationSeconds: 4 },
  { kind: "video", url: "https://media.mazarat-madinah.com/nabawi/38a55262f8.mp4", poster: "https://media.mazarat-madinah.com/nabawi/38a55262f8-poster-800.jpg", width: 720, height: 1280, durationSeconds: 7 },
  { kind: "video", url: "https://media.mazarat-madinah.com/nabawi/9c3bbcd5fc.mp4", poster: "https://media.mazarat-madinah.com/nabawi/9c3bbcd5fc-poster-800.jpg", width: 800, height: 450, durationSeconds: 13 },
  { kind: "photo", url: "https://media.mazarat-madinah.com/nabawi/141f5d6584-1600.webp", width: 1600, height: 900 },
  { kind: "video", url: "https://media.mazarat-madinah.com/nabawi/5b807f583c.mp4", poster: "https://media.mazarat-madinah.com/nabawi/5b807f583c-poster-800.jpg", width: 720, height: 1280, durationSeconds: 7 },
  { kind: "photo", url: "https://media.mazarat-madinah.com/nabawi/041aa58b16-1600.webp", width: 1600, height: 2844 },
  { kind: "photo", url: "https://media.mazarat-madinah.com/nabawi/9e3abc0a39-1600.webp", width: 1600, height: 2844 },
  { kind: "photo", url: "https://media.mazarat-madinah.com/nabawi/35061bba2d-1600.webp", width: 1600, height: 900 },
  { kind: "photo", url: "https://media.mazarat-madinah.com/nabawi/7595eb9846-1600.webp", width: 1600, height: 2844 },
  { kind: "photo", url: "https://media.mazarat-madinah.com/nabawi/32ea614a01-1600.webp", width: 1600, height: 900 },
  { kind: "photo", url: "https://media.mazarat-madinah.com/nabawi/9057fb6786-1600.webp", width: 1600, height: 900 },
  { kind: "photo", url: "https://media.mazarat-madinah.com/nabawi/759f2a4cca-1600.webp", width: 1600, height: 1200 },
  { kind: "photo", url: "https://media.mazarat-madinah.com/nabawi/e1dcbfabce-1600.webp", width: 1288, height: 1718 },
  { kind: "photo", url: "https://media.mazarat-madinah.com/nabawi/4cb98b47fc-1600.webp", width: 1600, height: 2133 },
  { kind: "video", url: "https://media.mazarat-madinah.com/nabawi/47fc552562.mp4", poster: "https://media.mazarat-madinah.com/nabawi/47fc552562-poster-800.jpg", width: 720, height: 1280, durationSeconds: 13 },
  { kind: "photo", url: "https://media.mazarat-madinah.com/nabawi/17660e5de0-1600.webp", width: 1080, height: 1920 },
  { kind: "photo", url: "https://media.mazarat-madinah.com/nabawi/e332522d1d-1600.webp", width: 1600, height: 1198 },
];
