// Generated by scripts/audio/install-narration.mts (npm run audio:install) — do not edit by hand.

/** Which recording of a stop: Arabic, the Arabic children's version, or English. */
export type NarrationVariant = "ar" | "kids-ar" | "en";

/** Recordings in public/audio/narration/, by file name without ".mp3". */
export const NARRATION_FILES: ReadonlySet<string> = new Set<string>([
  "hijra-1-ar",
  "hijra-1-en",
  "hijra-2-ar",
  "hijra-2-en",
  "hijra-3-ar",
  "hijra-3-en",
  "hijra-4-ar",
  "hijra-4-en",
]);

/** URL of a journey stop's recording, or null when there is none (the player then uses the device's voice). */
export function narrationSrc(journeySlug: string, stopOrder: number, variant: NarrationVariant): string | null {
  const name = `${journeySlug}-${stopOrder}-${variant}`;
  return NARRATION_FILES.has(name) ? `/audio/narration/${name}.mp3` : null;
}
