/**
 * install-narration — puts the recorded narration MP3s on the site.
 *
 *   npm run audio:install                 (MP3s from my_data/tts/mp3/)
 *   npm run audio:install -- <folder>     (MP3s from another folder)
 *
 * Copies every <journey>-<stop>-<ar|kids-ar|en>.mp3 (the names
 * export-narration.mts gave the texts) to public/audio/narration/, then
 * rewrites src/lib/narration-audio.ts from what that folder now holds: the
 * journey player plays a recording where one exists and the device's voice
 * everywhere else. Installed files stay installed — to remove one, delete it
 * from public/audio/narration/ and run this again. Commit both paths.
 *
 * A file whose name matches no exported text (my_data/tts/<name>.txt) is not
 * installed: it is almost always a typo in the slug or the stop number.
 */
import { existsSync } from "node:fs";
import { mkdir, readdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const FROM = path.resolve(ROOT, process.argv[2] ?? "my_data/tts/mp3");
const TEXTS = path.join(ROOT, "my_data/tts");
const DEST = path.join(ROOT, "public/audio/narration");
const MANIFEST = path.join(ROOT, "src/lib/narration-audio.ts");

/** <journey slug>-<stop sort_order>-<variant>.mp3; the slug may contain hyphens and digits. */
const NAME = /^[a-z0-9]+(?:-[a-z0-9]+)*-\d+-(?:ar|kids-ar|en)\.mp3$/;

/** An ID3 tag or an MPEG audio frame header — catches a WAV or a web page saved as .mp3. */
const isMp3 = (b: Buffer) => (b[0] === 0x49 && b[1] === 0x44 && b[2] === 0x33) || (b[0] === 0xff && (b[1] & 0xe0) === 0xe0);

const mb = (bytes: number) => `${(bytes / 1024 / 1024).toFixed(1)} MB`;

function manifest(names: string[]): string {
  const list = names.length ? `[\n${names.map((n) => `  "${n}",`).join("\n")}\n]` : "[]";
  return `// Generated by scripts/audio/install-narration.mts (npm run audio:install) — do not edit by hand.

/** Which recording of a stop: Arabic, the Arabic children's version, or English. */
export type NarrationVariant = "ar" | "kids-ar" | "en";

/** Recordings in public/audio/narration/, by file name without ".mp3". */
export const NARRATION_FILES: ReadonlySet<string> = new Set<string>(${list});

/** URL of a journey stop's recording, or null when there is none (the player then uses the device's voice). */
export function narrationSrc(journeySlug: string, stopOrder: number, variant: NarrationVariant): string | null {
  const name = \`\${journeySlug}-\${stopOrder}-\${variant}\`;
  return NARRATION_FILES.has(name) ? \`/audio/narration/\${name}.mp3\` : null;
}
`;
}

async function main() {
  await mkdir(DEST, { recursive: true });
  const texts = existsSync(TEXTS) ? (await readdir(TEXTS)).filter((f) => f.endsWith(".txt")) : [];
  const textNames = new Set(texts.map((f) => f.slice(0, -4)));

  const added: string[] = [];
  const updated: string[] = [];
  let unchanged = 0;
  const skipped: string[] = [];

  const incoming = existsSync(FROM) ? (await readdir(FROM)).filter((f) => f.toLowerCase().endsWith(".mp3")) : [];
  if (!existsSync(FROM)) console.warn(`No folder ${path.relative(ROOT, FROM)} — nothing to copy; refreshing the list only.`);

  for (const file of incoming.sort()) {
    const name = file.toLowerCase();
    if (!NAME.test(name)) {
      skipped.push(`${file}: the name is not <journey>-<stop>-<ar|kids-ar|en>.mp3`);
      continue;
    }
    const base = name.slice(0, -4);
    if (textNames.size && !textNames.has(base)) {
      skipped.push(`${file}: no stop has this name (no my_data/tts/${base}.txt) — check the slug and stop number`);
      continue;
    }
    const data = await readFile(path.join(FROM, file));
    if (!isMp3(data)) {
      skipped.push(`${file}: not an MP3 file`);
      continue;
    }
    const target = path.join(DEST, name);
    if (existsSync(target)) {
      if ((await readFile(target)).equals(data)) {
        unchanged++;
        continue;
      }
      updated.push(name);
    } else {
      added.push(name);
    }
    await writeFile(target, data);
  }

  // The list is rebuilt from what is installed, so earlier deliveries stay.
  const installed = (await readdir(DEST)).filter((f) => NAME.test(f)).sort();
  let bytes = 0;
  for (const f of installed) bytes += (await stat(path.join(DEST, f))).size;
  const names = installed.map((f) => f.slice(0, -4));
  const code = manifest(names);
  const before = existsSync(MANIFEST) ? await readFile(MANIFEST, "utf8") : "";
  if (code !== before) await writeFile(MANIFEST, code, "utf8");

  console.log(`Copied: ${added.length} new, ${updated.length} replaced, ${unchanged} unchanged.`);
  for (const n of added) console.log(`  + ${n}`);
  for (const n of updated) console.log(`  ~ ${n}`);
  if (skipped.length) {
    console.warn(`Not installed (${skipped.length}):`);
    for (const s of skipped) console.warn(`  ! ${s}`);
  }
  console.log(`Installed: ${installed.length} recordings, ${mb(bytes)} in public/audio/narration/.`);
  console.log(code === before ? "src/lib/narration-audio.ts already up to date." : "Rewrote src/lib/narration-audio.ts.");

  const installedSet = new Set(names);
  const missing = [...textNames].filter((n) => !installedSet.has(n)).sort();
  if (missing.length) {
    const shown = missing.slice(0, 12).join(", ");
    console.log(`Still to record: ${missing.length} — ${shown}${missing.length > 12 ? ", …" : ""}`);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
