/**
 * build-hero — processes the owner's selected المسجد النبوي photos into the
 * landing hero set.
 *
 * Usage:
 *   npx tsx scripts/build-hero.ts --dir "my_data/HERO_MASJAD_NABAWY/Selected_HERO"
 *
 * For each image it generates 400/800/1600 WebP variants (EXIF rotation
 * applied, metadata stripped) into public/hero/ and writes the manifest
 * src/lib/hero-images.ts that the landing page imports. The hero is a static
 * app asset on purpose: المسجد النبوي is the app's anchor, not one of its
 * "hidden places" — it must never appear in /places, /map or category counts.
 *
 * Re-run whenever the selection changes; output is fully regenerated.
 */
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { createHash } from "node:crypto";
import sharp from "sharp";
import { IMAGE_VARIANT_WIDTHS, LARGEST_VARIANT_WIDTH, WEBP_QUALITY } from "../src/lib/media-spec";

const IMAGE_EXTENSIONS = new Set([".jpg", ".jpeg", ".png", ".webp"]);
const OUT_DIR = path.join("public", "hero");
const MANIFEST = path.join("src", "lib", "hero-images.ts");

function parseDir(argv: string[]): string {
  const i = argv.indexOf("--dir");
  if (i === -1 || !argv[i + 1]) {
    console.error('Usage: npx tsx scripts/build-hero.ts --dir "<folder>"');
    process.exit(1);
  }
  return argv[i + 1];
}

async function main(): Promise<void> {
  const dir = parseDir(process.argv.slice(2));
  const files = (await readdir(dir))
    .filter((name) => IMAGE_EXTENSIONS.has(path.extname(name).toLowerCase()))
    .sort((a, b) => a.localeCompare(b));

  if (files.length === 0) {
    console.error(`No images found in: ${dir}`);
    process.exit(1);
  }

  await rm(OUT_DIR, { recursive: true, force: true });
  await mkdir(OUT_DIR, { recursive: true });

  const entries: { base: string; width: number; height: number }[] = [];

  for (const file of files) {
    const buffer = await readFile(path.join(dir, file));
    const base = `hero-${createHash("sha1").update(buffer).digest("hex").slice(0, 10)}`;
    // .rotate() applies EXIF orientation; sharp strips metadata by default.
    const pipeline = sharp(buffer).rotate();

    let outWidth = 0;
    let outHeight = 0;
    for (const width of IMAGE_VARIANT_WIDTHS) {
      const { data, info } = await pipeline
        .clone()
        .resize({ width, withoutEnlargement: true })
        .webp({ quality: WEBP_QUALITY })
        .toBuffer({ resolveWithObject: true });
      await writeFile(path.join(OUT_DIR, `${base}-${width}.webp`), data);
      if (width === LARGEST_VARIANT_WIDTH) {
        outWidth = info.width;
        outHeight = info.height;
      }
    }
    entries.push({ base, width: outWidth, height: outHeight });
    console.log(`processed ${file} -> ${base} (${outWidth}x${outHeight})`);
  }

  const manifest = `// GENERATED by scripts/build-hero.ts — do not edit by hand.
// Landing-hero photo set (المسجد النبوي الشريف), served from /public/hero.
// URLs follow the -400/-800/-1600.webp convention so PlaceImage's variantUrl
// and capMobile work unchanged.

export type HeroImage = { url: string; width: number; height: number };

export const HERO_IMAGES: HeroImage[] = [
${entries
  .map(
    (e) =>
      `  { url: "/hero/${e.base}-${LARGEST_VARIANT_WIDTH}.webp", width: ${e.width}, height: ${e.height} },`
  )
  .join("\n")}
];
`;
  await writeFile(MANIFEST, manifest);
  console.log(`\n${entries.length} hero image(s) -> ${OUT_DIR}, manifest -> ${MANIFEST}`);
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
